#Law of Large Numbers (homework) - S2, L15

#Test the Law of Large Numbers for N random normally distributed numbers with mean=0, stdev=1:
#Create an R script that will count how many of these numbers fall between -1 and 1 and divide by the total quality of N
#You know that E(X)=68.2%
#Check that Mean(XsubN)-> E(X) as you rerun your script while increasing N


rnorm(100)                #100 = number of numbers computer will generate


#HINT:
N<-_                      #specify sample size
counter<-_                #reset counter
for(i in rnorm(N)){       #iterate over vector of numbers; i is a variable (like x), which assumes each of the values generated by the computer using rnorm
  if(_ _ _ & _ _ _ ){     #check where iterate variable falls 
    counter<- _ _ _       #increase counter if condition is met
  }
}
answer<-counter/N         #calculate hit-ratio
answer                    #print answer in console

N<-1000000                #input; started with 100, then 1000, then 10000, then 1000000
counter<-0                #start counting at 0
for(i in rnorm(N)){
  if(i>-1 & i<1){
    counter<-counter+1
  }
}
counter/N

#compare to: 68.2% or 0.682

#as N increases, we get closer to 0.682



