#---------------- Histograms and Density Charts - S6, L66

#Histograms
s <- ggplot(data=movies, aes(x=BudgetMillions))
s + geom_histogram(binwidth=10)
     #count (y-axis) is generated by r; it's a statistic


#add colour
s + geom_histogram(binwidth=10, fill="Green")     #setting
s + geom_histogram(binwidth=10, aes(fill=Genre))  #mapping


#add a border
s + geom_histogram(binwidth=10, aes(fill=Genre), colour="Black")
      #color of fill is mapped to Genre
      #color of the borders is set to Black
#>>> Chart #3 (we will improve it later)



#Density Charts
# sometimes you may need them
s + geom_density(aes(fill=Genre))
s + geom_density(aes(fill=Genre), position="stack")
#another option: use + geom_area(position = "stack") if you have x and y vars:
#s + geom_density(aes(fill=Genre)) + geom_area(position="stack")


